# Generated by Django 5.0.3 on 2024-03-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.CharField(max_length=100),
        ),
    ]
